# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execution.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65xecution.proto\x12\nplayground\",\n\x0bTestRequest\x12\x0f\n\x07test_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"/\n\x0cTestResponse\x12\x0f\n\x07test_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t2S\n\rLocustService\x12\x42\n\x07RunTest\x12\x17.playground.TestRequest\x1a\x18.playground.TestResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'execution_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTREQUEST._serialized_start=31
  _TESTREQUEST._serialized_end=75
  _TESTRESPONSE._serialized_start=77
  _TESTRESPONSE._serialized_end=124
  _LOCUSTSERVICE._serialized_start=126
  _LOCUSTSERVICE._serialized_end=209
# @@protoc_insertion_point(module_scope)
