# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import execution_pb2 as execution__pb2


class LocustServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunTest = channel.stream_stream(
                '/playground.LocustService/RunTest',
                request_serializer=execution__pb2.TestRequest.SerializeToString,
                response_deserializer=execution__pb2.TestResponse.FromString,
                )


class LocustServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunTest(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocustServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunTest': grpc.stream_stream_rpc_method_handler(
                    servicer.RunTest,
                    request_deserializer=execution__pb2.TestRequest.FromString,
                    response_serializer=execution__pb2.TestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'playground.LocustService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LocustService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunTest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/playground.LocustService/RunTest',
            execution__pb2.TestRequest.SerializeToString,
            execution__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
